# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'PinboardPins' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PinboardPins
  
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'SwiftMessages'
    pod ‘IQCacheResources’


  target 'PinboardPinsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PinboardPinsUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
